#This program was created by Vishwa Nathan (vnathan@umich.edu) on June 28, 2019



#THIS FILE CONTAINS ALL THE CONSTANTS THAT THE USER CAN CHANGE.

#THE USER CAN CHANGE THE FOLLOWING THINGS
#1. ANYTHING RELATED TO THE STEPPER MOTOR
    #STEP ANGLE, MICROSTEPS PER STTETP,SCREW PITCH, THE DIRECTION AND PULSE PINS ON THE PI.
#2. THE GPIO PIN FOR THHE  LIMITSWITCH
#3. THE DIRECTIOION THATT THE MOTOR WILL MOVE. ETCHANT DIRECTION REFERS TO THE STAGE MOVING TOWARDS THE ETCH SOLUTION 
#   AND HOME DIRECTION REFERS TO THE STAGE MOVING AWAY FROM THE ETCHANT. SWAPPING THESE VALUES IS PERMITTED AND WILL FLIP THE DIRECTION THE STAGE MOVES. 
#   IF YOUR STAGE IS MOVING BACKWARDS TRY SWAPPING THE VALUES OF HOME_DIRECTION AND ETCHANT_DIRECTION
#4. WHETHER YOU HAVE AN LIMITSWITCH OR NOT. IF THERE IS NO LIMITSWITCH PRESENT SET ENDSTOP_ENABLED TO FALSE AND IF THERE IS A LIMITSWITCH SET ENDSTOP_ENABLED TO TRUE
#5. THE HOMING SPEED. YOU CAN MAKE THE STAGE HOME AT A FASTER OR SLOWER  RATE BY CHANGING THE HOMING VALUE.


import RPi.GPIO as GPIO #allows for use of GPIO pins





STEP_ANGLE = 1.8
#sets the number of microsteps per steps
MICROSTEPS_PER_STEP = 8
#sets the screw pitch of the lead screw in mm
SCREW_PITCH = 6
#Sets the pin used for the Direction Pin
DIR_PIN = 23
#Sets the pin used for the Pulse Pin
PULSE_PIN = 24
#Sets the pin for the limitswitch
LIMITSWITCH = 21
GPIO.setup(LIMITSWITCH, GPIO.IN, pull_up_down = GPIO.PUD_UP)
#These represent the direction the motor will move. 
#If the stage is not moving in the correct direction either swap the stepper motor wires or swap these values.
# (Set HOME_DIRECTION to 1 and ETCHANT_DIRECTION to 0)
HOME_DIRECTION =1
ETCHANT_DIRECTION =0


#Set this value to true if there is an endstop
ENDSTOP_ENABLED = False

#This value represents the homing speed
HOMING_SPEED = .00004